* Journalctl-mode

This is a major-mode for emacs to view systemd's journalctl output in emacs.
The output is split into chunks for performance reasons. 

Fontification is provided and may be customized.

At the moment it is still in very early development. Please give feedback on any problems that occure.

** Installation  

Clone the project or download journalctl-mode.el and put that file to a load-path.

Put  
down 
#+BEGIN_SRC  emacs-lisp
( require 'journalctl-mode) 
#+END_SRC

in your .emacs file.

** Usage

At the moment there are to functions provided to call journalctl: 

-   journalctl: will ask for commandline parameters like "-xe" and show the output in the  \ast{}journalctl\ast{} buffer.
- journalctl-boot: will provide you with the list of boots in the journal. You can choose one and view it in the buffer.
- journalctl-unit: will provide you with the list of units . You can choose one and view related logs  in the buffer.

In journalctl-mode you can navigate between the cunks with "n" (next chunk) and "p" (previous chunk).
I also redefined C-v and M-v so that it will move to the next chunk, when you have reached the bottom or top of the buffer.

You can add parameters from journalctl-mode with "+ +". 

There are also some keybindings to add parameters: 

- "+ r" : Reverse output (--reverse).
- "+ x": Augment log lines with explanation texts from the message catalog.  (--catalog).
- "+ s": Show  messages from system services and the kernel  only (--system).
- "+u": Show messages from service of current user only (--user).
- "+k": Show kernel message only (--kernel). This applies "- b".

- "+S": Show messages since given date and / or time (--since).
- "+U": Show messages until given date and / or time (--until).

You can edit the current parameters with "e".

You can grep on the current output of journalctl with "+ g". You will be asked for a pattern to grep.

You can remove all filters (grep) with "- -".

Type "q" to kill the "\ast{}journalctl\ast{}" buffer.
